version: '3.8'

services:
    backend:
      build: ./backend
      container_name: flask-backend
      ports:
        - "5000:5000"
      volumes:
        - ./backend:/app
      env_file:
        - ./backend/.env
      restart: unless-stopped


    frontend:
      build: ./frontend
      container_name: react-frontend
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules     # ← évite d'écraser les node_modules du conteneur
      restart: unless-stopped
      depends_on:
        - backend
