version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: flask run --host=0.0.0.0 --port=5000 --reload
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development



  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro  # Si tu fais un build React plus tard
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
